server:
  port: 8201

spring:
  application:
    name: proxy-zuul

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    register-with-eureka: true #注册到Eureka的注册中⼼,客户端注册
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://r1:7001/eureka/,http://r2:7002/eureka/ #配置注册中⼼地址
info:
  remark: 网关服务

zuul:
  routes: #给网关配置路由
    provider-exp-name:
      serviceId: provider-exp
      path: /providerExp/**
  ignored-services: provider-exp #关闭默认路由配置,禁用provider-exp路径访问